import { theme } from "@/constants/theme";

const colors = {
  light: {
    text: theme.colors.text,
    tint: theme.colors.primary,
    background: theme.colors.background,
    foreground: theme.colors.text,
    card: theme.colors.surface,
    cardForeground: theme.colors.text,
    primary: theme.colors.primary,
    primaryForeground: theme.colors.inkOnPrimary,
    secondary: theme.colors.secondary,
    secondaryForeground: theme.colors.white,
    muted: theme.colors.surfaceMuted,
    mutedForeground: theme.colors.textMuted,
    accent: theme.colors.healthSoft,
    accentForeground: theme.colors.health,
    destructive: theme.colors.error,
    destructiveForeground: theme.colors.white,
    border: theme.colors.border,
    input: theme.colors.input,
    success: theme.colors.success,
    warning: theme.colors.warning,
    info: theme.colors.info,
    health: theme.colors.health,
    healthSoft: theme.colors.healthSoft,
    primarySoft: theme.colors.primarySoft,
    secondarySoft: theme.colors.secondarySoft,
    warningSoft: theme.colors.warningSoft,
    errorSoft: theme.colors.errorSoft,
    white: theme.colors.white,
    overlay: theme.colors.overlay,
    gradient1: theme.colors.primary,
    gradient2: "#F0B75B",
    gradient3: "#F6D49B",
  },
  radius: theme.radius.md,
};

export default colors;
